/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Administrator
 */
public class hesap extends javax.swing.JFrame {

    /**
     * Creates new form hesap
     */double NumEnter1;
     double NumEnter2;
     double NumEnterResult;
     double Result;
     String Op;
    public hesap() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jbtnBS = new javax.swing.JButton();
        jtxtResult = new javax.swing.JTextField();
        jbtCE = new javax.swing.JButton();
        jbtnPM = new javax.swing.JButton();
        jbtnC = new javax.swing.JButton();
        jbtDigit8 = new javax.swing.JButton();
        jbtDigit7 = new javax.swing.JButton();
        jbtDigit9 = new javax.swing.JButton();
        jbtnPluss = new javax.swing.JButton();
        jbtDigit5 = new javax.swing.JButton();
        jbtDigit4 = new javax.swing.JButton();
        jbtDigit6 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jbtDigit2 = new javax.swing.JButton();
        jbtDigit1 = new javax.swing.JButton();
        jbtDigit3 = new javax.swing.JButton();
        jbtnPlus = new javax.swing.JButton();
        jbtnEquals = new javax.swing.JButton();
        jbtnDot = new javax.swing.JButton();
        jbtnDigit0 = new javax.swing.JButton();
        jButton20 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 153, 0));

        jPanel1.setBackground(new java.awt.Color(0, 51, 51));

        jbtnBS.setBackground(new java.awt.Color(0, 102, 102));
        jbtnBS.setFont(new java.awt.Font("Microsoft YaHei", 1, 36)); // NOI18N
        jbtnBS.setText("←");
        jbtnBS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnBSActionPerformed(evt);
            }
        });

        jtxtResult.setFont(new java.awt.Font("Microsoft YaHei", 1, 36)); // NOI18N
        jtxtResult.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jbtCE.setBackground(new java.awt.Color(0, 102, 102));
        jbtCE.setFont(new java.awt.Font("Microsoft YaHei", 1, 30)); // NOI18N
        jbtCE.setText("CE");
        jbtCE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtCEActionPerformed(evt);
            }
        });

        jbtnPM.setBackground(new java.awt.Color(0, 102, 102));
        jbtnPM.setFont(new java.awt.Font("Microsoft Tai Le", 1, 36)); // NOI18N
        jbtnPM.setText("÷ ");
        jbtnPM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnPMActionPerformed(evt);
            }
        });

        jbtnC.setBackground(new java.awt.Color(0, 102, 102));
        jbtnC.setFont(new java.awt.Font("Microsoft Tai Le", 1, 36)); // NOI18N
        jbtnC.setText("C");
        jbtnC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnCActionPerformed(evt);
            }
        });

        jbtDigit8.setBackground(new java.awt.Color(0, 255, 204));
        jbtDigit8.setFont(new java.awt.Font("Microsoft Tai Le", 1, 36)); // NOI18N
        jbtDigit8.setText("8");
        jbtDigit8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtDigit8ActionPerformed(evt);
            }
        });

        jbtDigit7.setBackground(new java.awt.Color(0, 255, 204));
        jbtDigit7.setFont(new java.awt.Font("Microsoft Tai Le", 1, 36)); // NOI18N
        jbtDigit7.setText("7");
        jbtDigit7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtDigit7ActionPerformed(evt);
            }
        });

        jbtDigit9.setBackground(new java.awt.Color(0, 255, 204));
        jbtDigit9.setFont(new java.awt.Font("Microsoft Tai Le", 1, 36)); // NOI18N
        jbtDigit9.setText("9");
        jbtDigit9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtDigit9ActionPerformed(evt);
            }
        });

        jbtnPluss.setBackground(new java.awt.Color(0, 102, 102));
        jbtnPluss.setFont(new java.awt.Font("Microsoft Tai Le", 1, 36)); // NOI18N
        jbtnPluss.setText("*");
        jbtnPluss.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnPlussActionPerformed(evt);
            }
        });

        jbtDigit5.setBackground(new java.awt.Color(0, 255, 204));
        jbtDigit5.setFont(new java.awt.Font("Microsoft Tai Le", 1, 36)); // NOI18N
        jbtDigit5.setText("5");
        jbtDigit5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtDigit5ActionPerformed(evt);
            }
        });

        jbtDigit4.setBackground(new java.awt.Color(0, 255, 204));
        jbtDigit4.setFont(new java.awt.Font("Microsoft Tai Le", 1, 36)); // NOI18N
        jbtDigit4.setText("4");
        jbtDigit4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtDigit4ActionPerformed(evt);
            }
        });

        jbtDigit6.setBackground(new java.awt.Color(0, 255, 204));
        jbtDigit6.setFont(new java.awt.Font("Microsoft Tai Le", 1, 36)); // NOI18N
        jbtDigit6.setText("6");
        jbtDigit6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtDigit6ActionPerformed(evt);
            }
        });

        jButton12.setBackground(new java.awt.Color(0, 102, 102));
        jButton12.setFont(new java.awt.Font("Microsoft Tai Le", 1, 36)); // NOI18N
        jButton12.setText("-");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });

        jbtDigit2.setBackground(new java.awt.Color(0, 255, 204));
        jbtDigit2.setFont(new java.awt.Font("Microsoft Tai Le", 1, 36)); // NOI18N
        jbtDigit2.setText("2");
        jbtDigit2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtDigit2ActionPerformed(evt);
            }
        });

        jbtDigit1.setBackground(new java.awt.Color(0, 255, 204));
        jbtDigit1.setFont(new java.awt.Font("Microsoft Tai Le", 1, 36)); // NOI18N
        jbtDigit1.setText("1");
        jbtDigit1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtDigit1ActionPerformed(evt);
            }
        });

        jbtDigit3.setBackground(new java.awt.Color(0, 255, 204));
        jbtDigit3.setFont(new java.awt.Font("Microsoft Tai Le", 1, 36)); // NOI18N
        jbtDigit3.setText("3");
        jbtDigit3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtDigit3ActionPerformed(evt);
            }
        });

        jbtnPlus.setBackground(new java.awt.Color(0, 102, 102));
        jbtnPlus.setFont(new java.awt.Font("Microsoft Tai Le", 1, 36)); // NOI18N
        jbtnPlus.setText("+");
        jbtnPlus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnPlusActionPerformed(evt);
            }
        });

        jbtnEquals.setBackground(new java.awt.Color(153, 255, 204));
        jbtnEquals.setFont(new java.awt.Font("Microsoft Tai Le", 1, 36)); // NOI18N
        jbtnEquals.setText("=");
        jbtnEquals.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnEqualsActionPerformed(evt);
            }
        });

        jbtnDot.setBackground(new java.awt.Color(0, 102, 102));
        jbtnDot.setFont(new java.awt.Font("Microsoft Tai Le", 1, 36)); // NOI18N
        jbtnDot.setText(".");
        jbtnDot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnDotActionPerformed(evt);
            }
        });

        jbtnDigit0.setBackground(new java.awt.Color(0, 255, 204));
        jbtnDigit0.setFont(new java.awt.Font("Microsoft Tai Le", 1, 36)); // NOI18N
        jbtnDigit0.setText("0");
        jbtnDigit0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnDigit0ActionPerformed(evt);
            }
        });

        jButton20.setBackground(new java.awt.Color(0, 102, 102));
        jButton20.setFont(new java.awt.Font("Microsoft Tai Le", 1, 36)); // NOI18N
        jButton20.setText("±");
        jButton20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton20ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jtxtResult)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addComponent(jbtDigit7, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jbtDigit8, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jbtDigit9, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jbtnPluss, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jButton20, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jbtnDigit0, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jbtnDot, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jbtnEquals, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jbtDigit1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jbtDigit2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jbtDigit3, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jbtnPlus, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jbtDigit4, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jbtDigit5, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jbtDigit6, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton12, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jbtnBS, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jbtCE, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jbtnC, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jbtnPM, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jtxtResult, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jbtCE, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jbtnC, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jbtnPM, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jbtnBS, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtDigit7, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtDigit8, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtDigit9, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtnPluss, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtDigit4, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtDigit5, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtDigit6, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton12, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtDigit1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtDigit2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtDigit3, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtnPlus, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton20, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtnDigit0, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtnDot, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtnEquals, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void EnterNumbers(String q)
    {
        String Nums = jtxtResult.getText() + q;
        jtxtResult.setText(Nums);
    }
    
    private void jbtDigit7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtDigit7ActionPerformed
    EnterNumbers("7");        // TODO add your handling code here:
    }//GEN-LAST:event_jbtDigit7ActionPerformed

    private void jbtDigit8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtDigit8ActionPerformed
    EnterNumbers("8");    // TODO add your handling code here:
    }//GEN-LAST:event_jbtDigit8ActionPerformed

    private void jbtDigit9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtDigit9ActionPerformed
    EnterNumbers("9");        // TODO add your handling code here:
    }//GEN-LAST:event_jbtDigit9ActionPerformed

    private void jbtDigit4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtDigit4ActionPerformed
    EnterNumbers("4");    // TODO add your handling code here:
    }//GEN-LAST:event_jbtDigit4ActionPerformed

    private void jbtDigit5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtDigit5ActionPerformed
    EnterNumbers("5");    // TODO add your handling code here:
    }//GEN-LAST:event_jbtDigit5ActionPerformed

    private void jbtDigit6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtDigit6ActionPerformed
    EnterNumbers("6");    // TODO add your handling code here:
    }//GEN-LAST:event_jbtDigit6ActionPerformed

    private void jbtDigit1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtDigit1ActionPerformed
    EnterNumbers("1");   // TODO add your handling code here:
    }//GEN-LAST:event_jbtDigit1ActionPerformed

    private void jbtDigit2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtDigit2ActionPerformed
     EnterNumbers("2");    // TODO add your handling code here:
    }//GEN-LAST:event_jbtDigit2ActionPerformed

    private void jbtDigit3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtDigit3ActionPerformed
       EnterNumbers("3");  // TODO add your handling code here:
    }//GEN-LAST:event_jbtDigit3ActionPerformed

    private void jbtnDigit0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnDigit0ActionPerformed
      EnterNumbers("0");   // TODO add your handling code here:
    }//GEN-LAST:event_jbtnDigit0ActionPerformed

    private void jbtnPMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnPMActionPerformed
     NumEnter1 = Double.parseDouble(jtxtResult.getText()); 
     jtxtResult.setText("");// TODO add your handling code here:
     Op ="/";
    }//GEN-LAST:event_jbtnPMActionPerformed

    private void jbtnPlussActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnPlussActionPerformed
   NumEnter1 = Double.parseDouble(jtxtResult.getText()); 
     jtxtResult.setText("");// TODO add your handling code here:
     Op ="*";     // TODO add your handling code here:
    }//GEN-LAST:event_jbtnPlussActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
       NumEnter1 = Double.parseDouble(jtxtResult.getText()); 
     jtxtResult.setText("");// TODO add your handling code here:
     Op ="-"; // TODO add your handling code here:
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jbtnPlusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnPlusActionPerformed
NumEnter1 = Double.parseDouble(jtxtResult.getText()); 
     jtxtResult.setText("");// TODO add your handling code here:
     Op ="+";        // TODO add your handling code here:
    }//GEN-LAST:event_jbtnPlusActionPerformed

    private void jbtnCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnCActionPerformed
        jtxtResult.setText(""); // TODO add your handling code here:
    }//GEN-LAST:event_jbtnCActionPerformed

    private void jbtCEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtCEActionPerformed
      jtxtResult.setText("");   // TODO add your handling code here:
      
      String Fn, Sn;
      
      Fn = String.valueOf(NumEnter1);
      Sn = String.valueOf(NumEnter2);
      
      Fn = ""; 
      Sn = "";
    }//GEN-LAST:event_jbtCEActionPerformed

    private void jButton20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton20ActionPerformed
      double nums = Double.parseDouble(String.valueOf(jtxtResult.getText()));
      nums = nums * (-1);
      jtxtResult.setText(String.valueOf(nums));
    }//GEN-LAST:event_jButton20ActionPerformed

    private void jbtnBSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnBSActionPerformed
        String backSp = null;
        
        if(jtxtResult.getText().length()> 0) ;
        {
            StringBuilder sb = new StringBuilder(jtxtResult.getText());
            sb.deleteCharAt(jtxtResult.getText().length() - 1);
            backSp = sb.toString();
            jtxtResult.setText(backSp);
        }
    }//GEN-LAST:event_jbtnBSActionPerformed

    private void jbtnDotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnDotActionPerformed
      if (! jtxtResult.getText().contains("."))
          jtxtResult.setText(jtxtResult.getText() + jbtnDot.getText());
    }//GEN-LAST:event_jbtnDotActionPerformed

    private void jbtnEqualsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnEqualsActionPerformed
        NumEnter2 = Double.parseDouble(jtxtResult.getText());
        if (Op == "+")
        {
            Result = NumEnter1 + NumEnter2;
            jtxtResult.setText(String.valueOf(Result));
        }
        else if (Op == "-")
        {
            Result = NumEnter1 - NumEnter2;
            jtxtResult.setText(String.valueOf(Result));
        }
        else if (Op == "*")
        {
            Result = NumEnter1 * NumEnter2;
            jtxtResult.setText(String.valueOf(Result));
        }
        else if (Op == "/")
        {
            Result = NumEnter1 / NumEnter2;
            jtxtResult.setText(String.valueOf(Result));
        }
    }//GEN-LAST:event_jbtnEqualsActionPerformed


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(hesap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(hesap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(hesap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(hesap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new hesap().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton20;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jbtCE;
    private javax.swing.JButton jbtDigit1;
    private javax.swing.JButton jbtDigit2;
    private javax.swing.JButton jbtDigit3;
    private javax.swing.JButton jbtDigit4;
    private javax.swing.JButton jbtDigit5;
    private javax.swing.JButton jbtDigit6;
    private javax.swing.JButton jbtDigit7;
    private javax.swing.JButton jbtDigit8;
    private javax.swing.JButton jbtDigit9;
    private javax.swing.JButton jbtnBS;
    private javax.swing.JButton jbtnC;
    private javax.swing.JButton jbtnDigit0;
    private javax.swing.JButton jbtnDot;
    private javax.swing.JButton jbtnEquals;
    private javax.swing.JButton jbtnPM;
    private javax.swing.JButton jbtnPlus;
    private javax.swing.JButton jbtnPluss;
    private javax.swing.JTextField jtxtResult;
    // End of variables declaration//GEN-END:variables
}
